import math

DEBUG = True

COMMANDER = "lukleh"

USERNAME = "twistedbot"
SERVER_HOST = "127.0.0.1"
SERVER_PORT = 25565

PROTOCOL_VERSION = 39 #minecraft version 1.3
NUMBER_OF_BLOCKS = 136
CONNECTION_MAX_DELAY = 20
CONNECTION_INITIAL_DELAY = 0.1 

WORLD_HEIGHT 			= 256
CHUNK_SIDE_LEN			= 16
PLAYER_HEIGHT           = 1.74
PLAYER_EYELEVEL         = 1.62
PLAYER_BODY_EXTEND      = 0.3

MAX_JUMP_HEIGHT			= 1.2
G						= -22.0 #18

SPEED_WALK   = 4.27
SPEED_SNEAK  = 1.31
SPEED_CLIMB  = 2.327272
SPEED_SPRINT = 5.6
SPEED_COBWEB = SPEED_WALK * 0.15
SPEED_JUMP   = math.sqrt(MAX_JUMP_HEIGHT*2/(-G)) * (-G)

JUMP_HEIGHT  = -0.5 * G * math.pow(SPEED_JUMP/G, 2)

COST_DIRECT		= 1 / SPEED_WALK
COST_DIAGONAL	= math.sqrt(2) / SPEED_WALK
COST_CLIMB		= 1 / SPEED_CLIMB

ANGLE_CHANGE_STEP		= 40
MAX_STEP_HEIGHT			= 0.5
TIME_STEP				= 0.05
DISTANCE_STEP			= SPEED_WALK * TIME_STEP

